# Generated by Django 3.1 on 2020-08-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GNP_realtime_start', models.DateField()),
                ('GNP_date', models.DateField()),
                ('GNP_value', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FRED',
            new_name='GDP',
        ),
        migrations.RenameField(
            model_name='gdp',
            old_name='FRED_date',
            new_name='GDP_date',
        ),
        migrations.RenameField(
            model_name='gdp',
            old_name='FRED_realtime_start',
            new_name='GDP_realtime_start',
        ),
        migrations.RenameField(
            model_name='gdp',
            old_name='FRED_value',
            new_name='GDP_value',
        ),
    ]
